import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/providers/ThemeProvider'
import './globals.css'
import GlobalContext from '@/context/GlobalContext'
import { ChildProps } from '@/types/children.interface'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            <GlobalContext>{children}</GlobalContext>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
